title: "Ozan Ağma"
description: "Öğrendiklerim."
author: "Ozan"
email: "ozanagma@gmail.com"
baseurl: ""
url: "https://ozanagma.github.io"

remote_theme: jekyll/minima

url: 'https://ozanagma.github.io/'
baseurl: ''